language: node_js
node_js:
  - stable
  - lts/*
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn --version
install:
  - yarn
  - yarn bootstrap
before_script:
  - cp services/web/.env.example services/web/.env
